import Mathlib.MeasureTheory.Function.FactorsThrough
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.MeasureTheory.Measure.Prokhorov
import Mathlib.MeasureTheory.Measure.LevyProkhorovMetric
import Mathlib.MeasureTheory.Measure.HasOuterApproxClosed
import Mathlib.MeasureTheory.Constructions.Polish.Basic

/-!
# Lemma 1 (Posterior process): factorization through Z (Part (ii))

Part of **Lemma 1 (Posterior process)** of the paper. The verbatim statement and proof are in
`docs/paper-lemma1.md` (the single source of truth).

The formalization reveals that the paper's single sentence packs two independent facts:

1. Doob–Dynkin itself (`factorization`): `σ(Z)`-measurable + standard-Borel codomain ⇒
   factorization. Given by Mathlib's `Measurable.exists_eq_measurable_comp`. Proved (no `sorry`).
2. `Δ(Θ)` is standard Borel (`deltaTheta_standardBorel`), because `Θ` is compact Polish. Mathlib
   only provides `MetrizableSpace (ProbabilityMeasure Θ)`, so this is proved from scratch here:
   `deltaTheta_polishSpace` (the weak topology is Polish — compact + metrizable) and
   `deltaTheta_borelSpace` (the Giry σ-algebra equals the Borel σ-algebra of the weak topology,
   both inclusions: `deltaTheta_borel_le_giry` via the test-function subbasis + second
   countability, and `deltaTheta_giry_le_borel` via `HasOuterApproxClosed` + a Dynkin argument).

`factorization_posterior` combines the two = the paper's `Δ(Θ)` version of Part (ii). All proved,
no `sorry`.
-/

open MeasureTheory TopologicalSpace Filter
open scoped NNReal BoundedContinuousFunction ENNReal Topology

namespace PosteriorProcess

/-- Doob–Dynkin factorization (the abstract content of Part (ii); proved). If `S : Ω → Δ` is
measurable w.r.t. `σ(Z)` (`Z : Ω → E`) and the codomain `Δ` is a standard Borel space, then
`S = f ∘ Z` for some measurable `f : E → Δ`. Directly from Mathlib's Doob–Dynkin lemma. -/
theorem factorization {Ω E Δ : Type*} [MeasurableSpace E]
    [MeasurableSpace Δ] [StandardBorelSpace Δ] [Nonempty Δ]
    (Z : Ω → E) (S : Ω → Δ)
    (hS : @Measurable Ω Δ (MeasurableSpace.comap Z inferInstance) inferInstance S) :
    ∃ f : E → Δ, Measurable f ∧ S = f ∘ Z :=
  hS.exists_eq_measurable_comp

/-- `Θ` compact Polish ⇒ `Δ(Θ) = ProbabilityMeasure Θ` carries a Polish topology (the weak
topology). Assembled from Mathlib: `ProbabilityMeasure Θ` is compact (Prokhorov) and metrizable
(Lévy–Prokhorov), and second-countable; a compact metrizable space is completely metrizable, hence
Polish. -/
theorem deltaTheta_polishSpace (Θ : Type*) [TopologicalSpace Θ] [PolishSpace Θ]
    [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ] :
    PolishSpace (ProbabilityMeasure Θ) := by
  letI : MetricSpace (ProbabilityMeasure Θ) :=
    TopologicalSpace.metrizableSpaceMetric (ProbabilityMeasure Θ)
  haveI : TopologicalSpace.IsCompletelyMetrizableSpace (ProbabilityMeasure Θ) := inferInstance
  infer_instance

/-- Each test-function evaluation `μ ↦ ∫⁻ f dμ` (as an `ℝ≥0`, `f : Θ →ᵇ ℝ≥0`) is measurable for
the Giry structure on `ProbabilityMeasure Θ`. These are the maps whose preimages form a subbasis
of the weak topology, so this is the engine of `deltaTheta_borel_le_giry`. -/
private theorem testAgainstNN_measurable {Θ : Type*} [TopologicalSpace Θ] [MeasurableSpace Θ]
    [OpensMeasurableSpace Θ] (f : Θ →ᵇ ℝ≥0) :
    Measurable (fun μ : ProbabilityMeasure Θ => μ.toFiniteMeasure.testAgainstNN f) := by
  have heq : (fun μ : ProbabilityMeasure Θ => μ.toFiniteMeasure.testAgainstNN f)
      = fun μ : ProbabilityMeasure Θ => (∫⁻ x, f x ∂(μ : Measure Θ)).toNNReal := by
    ext μ; rw [← ProbabilityMeasure.toWeakDualBCNN_apply]; rfl
  rw [heq]
  exact ((Measure.measurable_lintegral f.continuous.measurable.coe_nnreal_ennreal).comp
    measurable_subtype_coe).ennreal_toNNReal

/-- Direction `⊆`: the Borel σ-algebra of the weak topology is contained in the Giry structure.
The weak topology is the initial topology of the maps `μ ↦ testAgainstNN μ f` (`f : Θ →ᵇ ℝ≥0`), so
it is generated by the subbasis of their preimages of opens; each such preimage is Giry-measurable
(`testAgainstNN_measurable`), and `ProbabilityMeasure Θ` is second-countable, so
`borel_eq_generateFrom_of_subbasis` gives `borel ≤ Giry`. -/
theorem deltaTheta_borel_le_giry (Θ : Type*) [TopologicalSpace Θ] [PolishSpace Θ]
    [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ] :
    borel (ProbabilityMeasure Θ) ≤ (inferInstance : MeasurableSpace (ProbabilityMeasure Θ)) := by
  set S : Set (Set (ProbabilityMeasure Θ)) :=
    ⋃ f : Θ →ᵇ ℝ≥0,
      (fun U => (fun μ : ProbabilityMeasure Θ => μ.toFiniteMeasure.testAgainstNN f) ⁻¹' U) ''
        {U | IsOpen U} with hS
  have htop : (inferInstance : TopologicalSpace (ProbabilityMeasure Θ))
      = TopologicalSpace.generateFrom S := by
    have ha : (inferInstance : TopologicalSpace (ProbabilityMeasure Θ))
        = induced (fun μ : ProbabilityMeasure Θ => μ.toFiniteMeasure.testAgainstNN)
            Pi.topologicalSpace := by
      change induced ProbabilityMeasure.toFiniteMeasure
            (induced FiniteMeasure.toWeakDualBCNN
              (induced (fun (φ : WeakDual ℝ≥0 (Θ →ᵇ ℝ≥0)) f => φ f) Pi.topologicalSpace)) = _
      rw [induced_compose, induced_compose]; congr 1
    rw [hS, ha]
    simp only [Pi.topologicalSpace, induced_iInf, induced_compose, Function.comp_def]
    have key : ∀ f : Θ →ᵇ ℝ≥0,
        induced (fun μ : ProbabilityMeasure Θ => μ.toFiniteMeasure.testAgainstNN f)
            (inferInstance : TopologicalSpace ℝ≥0)
          = generateFrom ((fun U => (fun μ : ProbabilityMeasure Θ =>
              μ.toFiniteMeasure.testAgainstNN f) ⁻¹' U) '' {U | IsOpen U}) := by
      intro f
      conv_lhs => rw [← generateFrom_setOf_isOpen (inferInstance : TopologicalSpace ℝ≥0)]
      rw [induced_generateFrom_eq]
    simp_rw [key]
    rw [← generateFrom_iUnion]
  have hmeas : ∀ s ∈ S, MeasurableSet[inferInstance] s := by
    intro s hs
    simp only [hS, Set.mem_iUnion, Set.mem_image, Set.mem_setOf_eq] at hs
    obtain ⟨f, U, hU, rfl⟩ := hs
    exact (testAgainstNN_measurable f) hU.measurableSet
  calc borel (ProbabilityMeasure Θ)
      = MeasurableSpace.generateFrom S := borel_eq_generateFrom_of_subbasis htop
    _ ≤ _ := MeasurableSpace.generateFrom_le hmeas

/-- Direction `⊇`: the Giry structure is contained in the Borel σ-algebra of the weak topology.
The Giry structure is generated by the evaluations `μ ↦ μ s` (measurable `s`), so it suffices that
each is Borel for the weak topology. For closed `F`, `μ ↦ μ F = ⨅ₙ ∫⁻ (apprSeq F n) dμ` is a
countable infimum of the continuous maps `μ ↦ ∫⁻ · dμ` (`HasOuterApproxClosed` outer
approximation), hence Borel; this extends from the π-system of closed sets to all Borel sets by a
Dynkin argument. (Compactness of `Θ` is not needed here.) -/
theorem deltaTheta_giry_le_borel (Θ : Type*) [TopologicalSpace Θ] [PolishSpace Θ]
    [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ] :
    (inferInstance : MeasurableSpace (ProbabilityMeasure Θ)) ≤ borel (ProbabilityMeasure Θ) := by
  letI mb : MeasurableSpace (ProbabilityMeasure Θ) := borel (ProbabilityMeasure Θ)
  have hval : Measurable (fun μ : ProbabilityMeasure Θ => (μ : Measure Θ)) := by
    refine Measure.measurable_of_measurable_coe _ (fun s hs => ?_)
    refine MeasurableSpace.induction_on_inter
      (C := fun t _ => Measurable (fun μ : ProbabilityMeasure Θ => (μ : Measure Θ) t))
      (BorelSpace.measurable_eq.trans borel_eq_generateFrom_isClosed) isPiSystem_isClosed
      ?_ ?_ ?_ ?_ s hs
    · simp only [measure_empty]; exact measurable_const
    · -- closed `F`: `μ ↦ μ F` is a countable infimum of continuous integral maps
      intro F hF
      have heq : (fun μ : ProbabilityMeasure Θ => (μ : Measure Θ) F)
          = fun μ : ProbabilityMeasure Θ =>
              ⨅ n : ℕ, ∫⁻ x, (hF.apprSeq n x : ℝ≥0∞) ∂(μ : Measure Θ) := by
        ext μ
        refine le_antisymm (le_iInf fun n => HasOuterApproxClosed.measure_le_lintegral hF _ n) ?_
        exact ge_of_tendsto' (HasOuterApproxClosed.tendsto_lintegral_apprSeq hF _)
          (fun n => iInf_le _ n)
      rw [heq]
      refine Measurable.iInf fun n => ?_
      exact (ProbabilityMeasure.continuous_lintegral_boundedContinuousFunction
        (hF.apprSeq n)).borel_measurable
    · -- complement: `μ tᶜ = 1 - μ t`
      intro t htm ih
      have heq : (fun μ : ProbabilityMeasure Θ => (μ : Measure Θ) tᶜ)
          = fun μ : ProbabilityMeasure Θ => 1 - (μ : Measure Θ) t := by
        ext μ; rw [measure_compl htm (measure_ne_top _ _), measure_univ]
      rw [heq]; exact ih.const_sub 1
    · -- countable disjoint union: `μ (⋃ f) = ∑' μ (f i)`
      intro f hfd hfm ih
      have heq : (fun μ : ProbabilityMeasure Θ => (μ : Measure Θ) (⋃ i, f i))
          = fun μ : ProbabilityMeasure Θ => ∑' i, (μ : Measure Θ) (f i) := by
        ext μ; rw [measure_iUnion hfd hfm]
      rw [heq]; exact Measurable.tsum ih
  exact measurable_iff_comap_le.mp hval

/-- The Giry measurable structure on `ProbabilityMeasure Θ` coincides with the Borel σ-algebra of
the weak topology (`Θ` compact Polish). Classical fact (Kechris, *Classical Descriptive Set
Theory*, Thm 17.24; Parthasarathy). -/
theorem deltaTheta_borelSpace (Θ : Type*) [TopologicalSpace Θ] [PolishSpace Θ]
    [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ] :
    BorelSpace (ProbabilityMeasure Θ) :=
  ⟨le_antisymm (deltaTheta_giry_le_borel Θ) (deltaTheta_borel_le_giry Θ)⟩

/-- `Θ` compact Polish ⇒ `Δ(Θ) = ProbabilityMeasure Θ` is standard Borel. Assembles the Polish
topology (`deltaTheta_polishSpace`) with the identification of the Giry and Borel σ-algebras
(`deltaTheta_borelSpace`). -/
theorem deltaTheta_standardBorel (Θ : Type*) [TopologicalSpace Θ] [PolishSpace Θ]
    [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ] :
    StandardBorelSpace (ProbabilityMeasure Θ) :=
  letI := deltaTheta_borelSpace Θ
  letI := deltaTheta_polishSpace Θ
  ⟨⟨inferInstance, inferInstance, inferInstance⟩⟩

/-- Part (ii), full `Δ(Θ)` version: the abstract Doob–Dynkin factorization applied to the
posterior kernel `S : Ω → Δ(Θ)`. All logic is complete except the `deltaTheta_standardBorel`
gap; `Nonempty (Δ Θ)` is kept as a mild assumption. -/
theorem factorization_posterior {Ω E Θ : Type*} [MeasurableSpace E]
    [TopologicalSpace Θ] [PolishSpace Θ] [CompactSpace Θ] [MeasurableSpace Θ] [BorelSpace Θ]
    [Nonempty (ProbabilityMeasure Θ)]
    (Z : Ω → E) (S : Ω → ProbabilityMeasure Θ)
    (hS : @Measurable Ω (ProbabilityMeasure Θ) (MeasurableSpace.comap Z inferInstance)
      inferInstance S) :
    ∃ f : E → ProbabilityMeasure Θ, Measurable f ∧ S = f ∘ Z :=
  haveI := deltaTheta_standardBorel Θ
  factorization Z S hS

end PosteriorProcess
