/-
Copyright (c) 2026 <YOUR NAME>. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: <YOUR NAME>
-/
import Mathlib.MeasureTheory.Measure.Prokhorov
import Mathlib.MeasureTheory.Measure.LevyProkhorovMetric
import Mathlib.MeasureTheory.Measure.HasOuterApproxClosed
import Mathlib.MeasureTheory.Constructions.Polish.Basic

/-!
# The Borel σ-algebra of the weak topology on `ProbabilityMeasure`

`ProbabilityMeasure Ω` carries two structures that Mathlib so far kept apart:

* the **Giry measurable structure** (`ProbabilityMeasure.instMeasurableSpace`), the σ-algebra
  generated by the evaluation maps `μ ↦ μ s`, and
* the **weak topology** (`ProbabilityMeasure.instTopologicalSpace`, convergence in distribution).

This file proves that, for suitable `Ω`, the Giry σ-algebra *equals* the Borel σ-algebra of the
weak topology, i.e. `BorelSpace (ProbabilityMeasure Ω)`. As a consequence, when `Ω` is a compact
Polish space `ProbabilityMeasure Ω` is a `PolishSpace` and a `StandardBorelSpace`.

## Main results

* `ProbabilityMeasure.measurableSpace_le_borel`: `Giry ≤ borel`. Holds for any pseudometrizable
  Borel space `Ω`. Proof: it suffices that `μ ↦ μ s` is Borel for measurable `s`; for closed `F`,
  `μ ↦ μ F = ⨅ n, ∫⁻ (F.apprSeq n) dμ` (`HasOuterApproxClosed`) is a countable infimum of
  continuous maps, extended from closed sets to all Borel sets by a Dynkin argument.
* `ProbabilityMeasure.borel_le_measurableSpace`: `borel ≤ Giry`, assuming
  `SecondCountableTopology (ProbabilityMeasure Ω)`. Proof: the weak topology is the initial
  topology of the maps `μ ↦ μ.toFiniteMeasure.testAgainstNN f`; their preimages of opens form a
  Giry-measurable subbasis, and `borel_eq_generateFrom_of_subbasis` closes it.
* `ProbabilityMeasure.borelSpace`: the two combined.
* `ProbabilityMeasure.polishSpace` and `ProbabilityMeasure.standardBorelSpace`: the compact case.

## Implementation notes

The `SecondCountableTopology (ProbabilityMeasure Ω)` hypothesis of `borel_le_measurableSpace` is
currently only automatically available when `Ω` is compact (via `MetrizableSpace` + compactness).
Providing `SecondCountableTopology`/`SeparableSpace (ProbabilityMeasure Ω)` for a general separable
metrizable `Ω` would make `borelSpace` fire without compactness; see the TODO below.

## TODO

* `SecondCountableTopology (ProbabilityMeasure Ω)` for `Ω` separable metrizable.
* `PolishSpace (ProbabilityMeasure Ω)` for `Ω` (non-compact) Polish, via completeness of the
  Lévy–Prokhorov metric.
-/

open MeasureTheory TopologicalSpace Filter
open scoped NNReal BoundedContinuousFunction ENNReal Topology

namespace MeasureTheory.ProbabilityMeasure

variable {Ω : Type*} [TopologicalSpace Ω] [MeasurableSpace Ω]

/-- Each test-function evaluation `μ ↦ μ.toFiniteMeasure.testAgainstNN f` (`f : Ω →ᵇ ℝ≥0`) is
measurable for the Giry structure: it is `(∫⁻ f dμ).toNNReal`, and integration against a fixed
function is Giry-measurable (`Measure.measurable_lintegral`). -/
theorem measurable_testAgainstNN [OpensMeasurableSpace Ω] (f : Ω →ᵇ ℝ≥0) :
    Measurable (fun μ : ProbabilityMeasure Ω => μ.toFiniteMeasure.testAgainstNN f) := by
  have heq : (fun μ : ProbabilityMeasure Ω => μ.toFiniteMeasure.testAgainstNN f)
      = fun μ : ProbabilityMeasure Ω => (∫⁻ x, f x ∂(μ : Measure Ω)).toNNReal := by
    ext μ; rw [← ProbabilityMeasure.toWeakDualBCNN_apply]; rfl
  rw [heq]
  exact ((Measure.measurable_lintegral f.continuous.measurable.coe_nnreal_ennreal).comp
    measurable_subtype_coe).ennreal_toNNReal

/-- The Borel σ-algebra of the weak topology is contained in the Giry structure. The weak topology
is the initial topology of the maps `μ ↦ μ.toFiniteMeasure.testAgainstNN f` (`f : Ω →ᵇ ℝ≥0`), so it
is generated by the subbasis of their preimages of opens; each such preimage is Giry-measurable, and
second countability lets `borel_eq_generateFrom_of_subbasis` conclude. -/
theorem borel_le_measurableSpace [OpensMeasurableSpace Ω]
    [SecondCountableTopology (ProbabilityMeasure Ω)] :
    borel (ProbabilityMeasure Ω) ≤ (inferInstance : MeasurableSpace (ProbabilityMeasure Ω)) := by
  set S : Set (Set (ProbabilityMeasure Ω)) :=
    ⋃ f : Ω →ᵇ ℝ≥0,
      (fun U => (fun μ : ProbabilityMeasure Ω => μ.toFiniteMeasure.testAgainstNN f) ⁻¹' U) ''
        {U | IsOpen U} with hS
  have htop : (inferInstance : TopologicalSpace (ProbabilityMeasure Ω))
      = TopologicalSpace.generateFrom S := by
    have ha : (inferInstance : TopologicalSpace (ProbabilityMeasure Ω))
        = induced (fun μ : ProbabilityMeasure Ω => μ.toFiniteMeasure.testAgainstNN)
            Pi.topologicalSpace := by
      change induced ProbabilityMeasure.toFiniteMeasure
            (induced FiniteMeasure.toWeakDualBCNN
              (induced (fun (φ : WeakDual ℝ≥0 (Ω →ᵇ ℝ≥0)) f => φ f) Pi.topologicalSpace)) = _
      rw [induced_compose, induced_compose]; congr 1
    rw [hS, ha]
    simp only [Pi.topologicalSpace, induced_iInf, induced_compose, Function.comp_def]
    have key : ∀ f : Ω →ᵇ ℝ≥0,
        induced (fun μ : ProbabilityMeasure Ω => μ.toFiniteMeasure.testAgainstNN f)
            (inferInstance : TopologicalSpace ℝ≥0)
          = generateFrom ((fun U => (fun μ : ProbabilityMeasure Ω =>
              μ.toFiniteMeasure.testAgainstNN f) ⁻¹' U) '' {U | IsOpen U}) := by
      intro f
      conv_lhs => rw [← generateFrom_setOf_isOpen (inferInstance : TopologicalSpace ℝ≥0)]
      rw [induced_generateFrom_eq]
    simp_rw [key]
    rw [← generateFrom_iUnion]
  have hmeas : ∀ s ∈ S, MeasurableSet[inferInstance] s := by
    intro s hs
    simp only [hS, Set.mem_iUnion, Set.mem_image, Set.mem_setOf_eq] at hs
    obtain ⟨f, U, hU, rfl⟩ := hs
    exact (measurable_testAgainstNN f) hU.measurableSet
  calc borel (ProbabilityMeasure Ω)
      = MeasurableSpace.generateFrom S := borel_eq_generateFrom_of_subbasis htop
    _ ≤ _ := MeasurableSpace.generateFrom_le hmeas

/-- The Giry structure is contained in the Borel σ-algebra of the weak topology. It suffices that
`μ ↦ μ s` is Borel for every measurable `s`; for closed `F`, `μ ↦ μ F = ⨅ n, ∫⁻ (F.apprSeq n) dμ`
(`HasOuterApproxClosed`) is a countable infimum of the continuous maps `μ ↦ ∫⁻ · dμ`, and this
extends from the π-system of closed sets to all Borel sets by a Dynkin argument. -/
theorem measurableSpace_le_borel [PseudoMetrizableSpace Ω] [BorelSpace Ω] :
    (inferInstance : MeasurableSpace (ProbabilityMeasure Ω)) ≤ borel (ProbabilityMeasure Ω) := by
  letI mb : MeasurableSpace (ProbabilityMeasure Ω) := borel (ProbabilityMeasure Ω)
  have hval : Measurable (fun μ : ProbabilityMeasure Ω => (μ : Measure Ω)) := by
    refine Measure.measurable_of_measurable_coe _ (fun s hs => ?_)
    refine MeasurableSpace.induction_on_inter
      (C := fun t _ => Measurable (fun μ : ProbabilityMeasure Ω => (μ : Measure Ω) t))
      (BorelSpace.measurable_eq.trans borel_eq_generateFrom_isClosed) isPiSystem_isClosed
      ?_ ?_ ?_ ?_ s hs
    · simp only [measure_empty]; exact measurable_const
    · intro F hF
      have heq : (fun μ : ProbabilityMeasure Ω => (μ : Measure Ω) F)
          = fun μ : ProbabilityMeasure Ω =>
              ⨅ n : ℕ, ∫⁻ x, (hF.apprSeq n x : ℝ≥0∞) ∂(μ : Measure Ω) := by
        ext μ
        refine le_antisymm (le_iInf fun n => HasOuterApproxClosed.measure_le_lintegral hF _ n) ?_
        exact ge_of_tendsto' (HasOuterApproxClosed.tendsto_lintegral_apprSeq hF _)
          (fun n => iInf_le _ n)
      rw [heq]
      refine Measurable.iInf fun n => ?_
      exact (ProbabilityMeasure.continuous_lintegral_boundedContinuousFunction
        (hF.apprSeq n)).borel_measurable
    · intro t htm ih
      have heq : (fun μ : ProbabilityMeasure Ω => (μ : Measure Ω) tᶜ)
          = fun μ : ProbabilityMeasure Ω => 1 - (μ : Measure Ω) t := by
        ext μ; rw [measure_compl htm (measure_ne_top _ _), measure_univ]
      rw [heq]; exact ih.const_sub 1
    · intro f hfd hfm ih
      have heq : (fun μ : ProbabilityMeasure Ω => (μ : Measure Ω) (⋃ i, f i))
          = fun μ : ProbabilityMeasure Ω => ∑' i, (μ : Measure Ω) (f i) := by
        ext μ; rw [measure_iUnion hfd hfm]
      rw [heq]; exact Measurable.tsum ih
  exact measurable_iff_comap_le.mp hval

/-- The Giry σ-algebra on `ProbabilityMeasure Ω` is the Borel σ-algebra of the weak topology. -/
instance borelSpace [PseudoMetrizableSpace Ω] [BorelSpace Ω]
    [SecondCountableTopology (ProbabilityMeasure Ω)] : BorelSpace (ProbabilityMeasure Ω) :=
  ⟨le_antisymm measurableSpace_le_borel borel_le_measurableSpace⟩

section Compact

variable [PolishSpace Ω] [CompactSpace Ω] [BorelSpace Ω]

/-- For compact Polish `Ω`, the weak topology on `ProbabilityMeasure Ω` is Polish: it is compact
(Prokhorov) and metrizable (Lévy–Prokhorov) and second countable, hence completely metrizable. -/
theorem polishSpace : PolishSpace (ProbabilityMeasure Ω) := by
  letI : MetricSpace (ProbabilityMeasure Ω) :=
    TopologicalSpace.metrizableSpaceMetric (ProbabilityMeasure Ω)
  haveI : TopologicalSpace.IsCompletelyMetrizableSpace (ProbabilityMeasure Ω) := inferInstance
  infer_instance

/-- For compact Polish `Ω`, `ProbabilityMeasure Ω` is a standard Borel space. -/
instance standardBorelSpace : StandardBorelSpace (ProbabilityMeasure Ω) :=
  letI := polishSpace (Ω := Ω)
  inferInstance

end Compact

end MeasureTheory.ProbabilityMeasure
