#!/usr/bin/env python3
"""把每个 blueprint 节点的 Lean 陈述内联进节点里(逐字,由 Lean 自己打印)。

动机:节点里的散文是**人写的转述**,转述层正是论文↔Lean 漂移的藏身处。
让读者在同一处看到 Lean 内核实际认可的陈述,就不必信转述、不必点开 docgen。

保证:陈述由 `#check @Decl` 的输出直接嵌入,脚本可反复重跑 ⇒ 结构上不可能漂移。
用法:python3 tools/gen_lean_statements.py   (在 my_proofs 目录下)
"""
import re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "blueprint" / "src"
FILES = ["content.tex", "model.tex"]
BEGIN = "% BEGIN-LEAN-STMT (auto-generated by tools/gen_lean_statements.py -- do not edit)"
END = "% END-LEAN-STMT"

VERB = re.compile(r"\\begin\{verbatim\}.*?\\end\{verbatim\}", re.S)
def _mask(t):
    store = []
    def f(m):
        store.append(m.group(0)); return f"@@VERB{len(store)-1}@@"
    return VERB.sub(f, t), store
def _unmask(t, store):
    for i, s in enumerate(store):
        t = t.replace(f"@@VERB{i}@@", s)
    return t

ENVS = ("lemma", "step", "definition", "faithcheck", "theorem", "proposition")

def strip_block(body: str) -> str:
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", body, flags=re.S)

def node_iter(text: str):
    pat = re.compile(r"\\begin\{(" + "|".join(ENVS) + r")\}(.*?)\\end\{\1\}", re.S)
    return pat

# 1) 收集所有节点用到的声明
decls, per_file, stores = [], {}, {}
for fn in FILES:
    t, stores[fn] = _mask((SRC / fn).read_text(encoding="utf-8"))
    per_file[fn] = t
    for m in node_iter(t).finditer(t):
        lm = re.search(r"\\lean\{([^}]*)\}", m.group(2))
        if lm:
            for d in lm.group(1).replace("\n", " ").split(","):
                d = d.strip()
                if d and d not in decls:
                    decls.append(d)
if not decls:
    sys.exit("未找到任何 \\lean{} 声明")

# 2) 让 Lean 自己打印每条陈述(用哨兵分隔,便于精确切分)
lean_src = "import MyProofs\n" + "".join(
    f'#eval IO.println "@@@{d}"\n#check @{d}\n' for d in decls)
tmp = ROOT / ".lean_stmt_tmp.lean"
tmp.write_text(lean_src, encoding="utf-8")
try:
    out = subprocess.run(["lake", "env", "lean", str(tmp)], cwd=ROOT,
                         capture_output=True, text=True).stdout
finally:
    tmp.unlink(missing_ok=True)

# 3) 按哨兵切分出每条声明的陈述
stmts = {}
cur = None
for line in out.split("\n"):
    s = line.strip()
    if s.startswith("@@@"):
        cur = s[3:]; stmts[cur] = []
    elif cur is not None:
        stmts[cur].append(line)
for k in stmts:
    stmts[k] = "\n".join(stmts[k]).strip("\n").rstrip()

missing = [d for d in decls if not stmts.get(d)]
if missing:
    sys.exit(f"以下声明没取到陈述(名字写错或未 import?): {missing}")

# 4) 内联回节点(先剥旧块,保证幂等)
total = 0
for fn in FILES:
    t = per_file[fn]
    def repl(m):
        global total
        kind, body = m.group(1), strip_block(m.group(2))
        lm = re.search(r"\\lean\{([^}]*)\}", body)
        if not lm:
            return f"\\begin{{{kind}}}{body}\\end{{{kind}}}"
        ds = [d.strip() for d in lm.group(1).replace("\n", " ").split(",") if d.strip()]
        blocks = "\n".join(f"\\begin{{verbatim}}\n{stmts[d]}\n\\end{{verbatim}}" for d in ds)
        total += 1
        note = ("\\par\\smallskip\\noindent\\textbf{Lean statement" +
                ("s" if len(ds) > 1 else "") +
                " (printed by Lean; verbatim):}\n")
        return (f"\\begin{{{kind}}}{body.rstrip()}\n\n{BEGIN}\n{note}{blocks}\n{END}\n"
                f"\\end{{{kind}}}")
    t = node_iter(t).sub(repl, t)
    (SRC / fn).write_text(_unmask(t, stores[fn]), encoding="utf-8")
print(f"已内联 {total} 个节点, {len(decls)} 条声明")
