#!/usr/bin/env python3
"""把论文原文逐字内联进对应的 blueprint 节点(与 Lean 陈述并排)。

动机:节点里论文侧原本也是**我写的转述**。Lean 侧已由 gen_lean_statements.py 逐字化,
论文侧若仍是转述,读者仍需信一次转述。两侧都逐字后,节点内即可完成免信任比对。

做法:按行区间从正稿精确切片(与 docs/paper-model.md 同一套纪律),并断言每一片
都是正稿的逐字子串;以 verbatim 展示论文**源码**,故不受论文自定义宏(\\T \\F \\Sel)影响。
正稿在仓库外 ../paper-source/(私密,不入库),故本脚本只在本地可跑;生成结果入库。

用法:python3 tools/gen_paper_statements.py   (在 my_proofs 目录下)
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "blueprint" / "src"
TEX = ROOT.parent / "paper-source" / "MDC-new-application-screening.tex"
BEGIN = "% BEGIN-PAPER-STMT (auto-generated by tools/gen_paper_statements.py -- do not edit)"
END = "% END-PAPER-STMT"

VERB = re.compile(r"\\begin\{verbatim\}.*?\\end\{verbatim\}", re.S)
def _mask(t):
    store = []
    def f(m):
        store.append(m.group(0)); return f"@@VERB{len(store)-1}@@"
    return VERB.sub(f, t), store
def _unmask(t, store):
    for i, s in enumerate(store):
        t = t.replace(f"@@VERB{i}@@", s)
    return t

ENVS = ("lemma", "step", "definition", "faithcheck", "theorem", "proposition")

# blueprint 标签 -> 正稿行区间(含端点)。只映射**确实是论文陈述**的节点;
# Step / Faithfulness check / 纯接口节点没有论文对应物,故意留空。
MAP = {
 "lem:posterior-martingale": [(1154, 1174)],   # 论文 Lemma 1 陈述
 "def:setup":                [(216, 216)],     # Environment
 "def:allocdate":            [(224, 230)],     # Timeline(τ)
 "def:singleshot":           [(220, 222)],     # Assumption 1(节点明说未承载它)
 "def:selections":           [(348, 349)],     # Sel(𝓡ₜ^Γ)
 "def:contvalue":            [(348, 361)],     # U_t 的定义式
 "def:truncvalue":           [(903, 924)],     # V_t 的定义式
 "def:collapse":             [(422, 430), (442, 447)],  # 状态分解 + collapse
}

if not TEX.exists():
    sys.exit(f"找不到正稿 {TEX}(它在仓库外,私密)。生成结果已入库,无需重跑即可构建。")
L = TEX.read_text(encoding="utf-8").split("\n")
FULL = "\n".join(L)

def slice_(a, b):
    s = "\n".join(L[a-1:b]).rstrip()
    assert s in FULL, f"切片 {a}-{b} 不是正稿逐字子串"
    return s

def strip_block(body):
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", body, flags=re.S)

pat = re.compile(r"\\begin\{(" + "|".join(ENVS) + r")\}(?:\[.*?\])?(.*?)\\end\{\1\}", re.S)
seen, total = set(), 0
for fn in ["content.tex", "model.tex"]:
    t, _store = _mask((SRC / fn).read_text(encoding="utf-8"))
    def repl(m):
        global total
        kind, body = m.group(1), strip_block(m.group(2))
        lm = re.search(r"\\label\{([^}]*)\}", body)
        lab = lm.group(1) if lm else None
        if lab not in MAP:
            return m.group(0).replace(m.group(2), body)
        seen.add(lab)
        blocks = "\n".join(f"\\begin{{verbatim}}\n{slice_(a,b)}\n\\end{{verbatim}}"
                           for a, b in MAP[lab])
        note = ("\\par\\smallskip\\noindent\\textbf{Paper text (verbatim from the manuscript "
                "source):}\n")
        block = f"{BEGIN}\n{note}{blocks}\n{END}\n"
        # 论文块放在 Lean 块之前:先看论文怎么说,再看 Lean 说什么
        if "% BEGIN-LEAN-STMT" in body:
            # 吞掉前导换行并固定为两个,否则每次重跑都会多留一个空行(幂等性 bug)
            body = re.sub(r"\n*% BEGIN-LEAN-STMT",
                          lambda m: "\n\n" + block + "% BEGIN-LEAN-STMT", body, count=1)
            total += 1
            return f"\\begin{{{kind}}}{body}\\end{{{kind}}}"
        total += 1
        return f"\\begin{{{kind}}}{body.rstrip()}\n\n{block}\\end{{{kind}}}"
    # 保留可能的 [title] 参数
    def repl2(m):
        head = m.group(0)[:m.group(0).index(m.group(2))]
        kind, body = m.group(1), strip_block(m.group(2))
        lm = re.search(r"\\label\{([^}]*)\}", body)
        lab = lm.group(1) if lm else None
        if lab not in MAP:
            return head + body + f"\\end{{{kind}}}"
        seen.add(lab)
        global total
        blocks = "\n".join(f"\\begin{{verbatim}}\n{slice_(a,b)}\n\\end{{verbatim}}"
                           for a, b in MAP[lab])
        note = ("\\par\\smallskip\\noindent\\textbf{Paper text (verbatim from the manuscript "
                "source):}\n")
        block = f"{BEGIN}\n{note}{blocks}\n{END}\n"
        total += 1
        if "% BEGIN-LEAN-STMT" in body:
            # 吞掉前导换行并固定为两个,否则每次重跑都会多留一个空行(幂等性 bug)
            body = re.sub(r"\n*% BEGIN-LEAN-STMT",
                          lambda m: "\n\n" + block + "% BEGIN-LEAN-STMT", body, count=1)
            return head + body + f"\\end{{{kind}}}"
        return head + body.rstrip() + "\n\n" + block + f"\\end{{{kind}}}"
    t = pat.sub(repl2, t)
    (SRC / fn).write_text(_unmask(t, _store), encoding="utf-8")

missing = set(MAP) - seen
if missing:
    sys.exit(f"以下映射的 blueprint 标签不存在(映射已过期): {sorted(missing)}")
print(f"已内联论文原文到 {total} 个节点,全部切片经逐字校验通过")
